### ISSUE TITLE
Upgrade todo list after alpha version

### ISSUE THREAD

**Issue by leej1230** [leej1230/ECS193A-prototype#31]
I am writing a list here to not forget about it. Feel free to add yours, but don't forget to either delete or check once it is done.

- [x] DatasetPage.js uses class component. Swap to function component, maintain functionality.
- [x] Refactor view.py. Since we didn't really delete any code up until now, APIs are like huge snowball right now. Ideally views.py should be as simple as possible so that anyone who reads the code can easily read through.
- [x] Search in main page. Even with sample dataset, it was containing 10,000 of genes. Instead of listing them out, I want to have a search engine.
